jobs:
- job: Linux_CI
  timeoutInMinutes: 90
  displayName: 'Linux CI'
  pool:
    vmImage: 'ubuntu-22.04'
  strategy:
    matrix:
      Py311:
        python.version: '3.11'
      Py312:
        python.version: '3.12'

  variables:
    PYTHONUNBUFFERED: '1'
    CCACHE_DIR: $(Pipeline.Workspace)/ccache

  steps:
  - checkout: self
    submodules: recursive

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      sudo apt-get update -y
      sudo apt-get install -y build-essential ccache
      sudo apt-get remove libunwind-* # Required to install libgstreamer
      sudo apt-get install -y libgtk-3-dev libjpeg-dev libtiff-dev \
              libsdl2-dev libgstreamer-plugins-base1.0-dev libnotify-dev \
              libsm-dev libwebkit2gtk-4.0-dev libxtst-dev libexpat1-dev \
              libgl1-mesa-dev libglu1-mesa-dev libcurl4-openssl-dev \
              libgstreamer-plugins-bad1.0-dev
      echo "##vso[task.prependpath]/usr/lib/ccache"
    displayName: 'Install deb package requirements & setup ccache'

  - task: Cache@2
    inputs:
      key: 'ccache | "$(Agent.OS)" | "$(python.version)" | "$(Build.BuildNumber)"'
      path: $(CCACHE_DIR)
      restoreKeys: |
        ccache | "$(Agent.OS)" | "$(python.version)"
    displayName: ccache

  - script: |
      python -m pip install -U pip setuptools wheel auditwheel
      python -m pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  - script: |
      python build.py --jobs=4 build_wx
    displayName: 'build wxWidgets'

  - script: |
      python build.py dox etg --nodoc sip
    displayName: 'generate code'

  - script: |
      python build.py --jobs=4 build_py
    displayName: 'build wxPython'

  - script: |
      python build.py bdist_wheel
    displayName: 'build platform specific wheel'

  - script: |
      auditwheel repair --plat manylinux_2_35_x86_64 --only-plat -w dist dist/wxPythonMeticy-*.whl
    displayName: 'build manylinux'

  - script: |
      python -m pip install dist/wxPythonMeticy-*manylinux*.whl
      python -c "import wx; print(f'Successfully tested importing wx version {wx.version()}');"
    displayName: 'test install'
    
  - task: TwineAuthenticate@1
    inputs:
      artifactFeed: wxPythonMeticy/release_artifacts
    displayName: 'Twine Authenticate'

  - script: |
      python -m twine upload -r release_artifacts --config-file $(PYPIRC_PATH) dist/wxPythonMeticy-*manylinux*
    displayName: 'Upload to feed'