# Publishes files associated with a release to PyPI

name: Publish to wxPython-Meticy package in PyPI 

on:
  release:
    types: [published, edited] # The action runs when we publish a release

jobs:

  publish-to-pypi:
    name: Publish dist to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/wxPythonMeticy  
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download wheels
      uses: robinraju/release-downloader@v1.9
      with:
        tag: ${{ github.ref_name }}
        fileName: "*.whl"
        out-file-path: dist
    - name: Download tar gz
      uses: robinraju/release-downloader@v1.9
      with:
        tag: ${{ github.ref_name }}
        fileName: "*.tar.gz"
        out-file-path: dist
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
